### ISSUE TITLE
First load of dashboards causes video thumbnails to expand at different sizes

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/tennotv#32]
### Tenno.tv Issue
---

**Summary (short):**
The initial dashboard load has thumbnails that are mis-sized, a window resize fixes the issue.

---
**If issue, Reproduction:**
1. Load the site, not all thumbs match size.
2. Adjust size
3. It's fixed

---
**Mockups, screenshots, evidence:**

![image](https://user-images.githubusercontent.com/7128721/50785917-a62ebd80-1277-11e9-84f7-a2069958a8ec.png)

**Comment by TobiTenno** [comment]
I think it's because we don't set a size for them, so they try to just fit in. I'd start in [dashControl.js](https://github.com/WFCD/tennotv/blob/master/assets/js/dashControl.js) and [dashboard.hbs](https://github.com/WFCD/tennotv/blob/master/views/dashboard.hbs)

**Comment by Pckool** [comment]
It should be fixed with my latest commit here: https://github.com/Pckool/tennotv

**Comment by TobiTenno** [comment]
could you make a [pull request](https://github.com/WFCD/tennotv/compare)?

**Comment by Pckool** [comment]
Done.
